Repository tycrek/ass, pull requests merged in 2021-10, with the labels that each got.

#76 Switched to `discord-webhook-node`, dropping `discord.js` for webhooks (closes #74)
  README.md
  package-lock.json
  package.json
  routers/upload.js
Labels: enhancement

#77 Added check for duplicate ID's (closes #75)
  routers/upload.js
Labels: bug

#79 Fixed webhooks oops
  routers/upload.js
Labels: bug

#73 Printf
  flameshot_example.sh
Labels: enhancement

#80 Added `.github/autoapproval.yml` for auto-approve bot
  .github/autoapproval.yml
Labels: enhancement, tycrek

#82 Only load custom index if exported function is detected
  ass.js
Labels: enhancement, tycrek

#83 Minor updates to a few community health files
  .github/CONTRIBUTING.md
  .github/README.md
  .github/SUPPORT.md
  _.npmrc
  sample_config.sxcu
Labels: documentation, tycrek

#84 Updated packages
  package-lock.json
  package.json
Labels: tycrek

#85 Fixed custom index loading trying to load as Boolean
  ass.js
Labels: bug, tycrek

#87 Fixed incorrect path check for custom index (cherry picked from ts branch)
  .github/README.md
  ass.js
Labels: bug, enhancement, tycrek

#88 🕛 added a header for setting the time offset (closes #63)
  .github/README.md
  routers/resource.js
  routers/upload.js
  utils.js
Labels: enhancement
